//go:build ignore

// 校验直插数据库的 clients / client_deployment_profiles 行能否被 GORM 正常读出。
// 用法：go run ./tools/verify_client_row.go <sqlite-file>
package main

import (
	"fmt"
	"os"

	"github.com/nuomiiiii/lite/database/models"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	path := "./data/lite.db"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	db, err := gorm.Open(sqlite.Open(path), &gorm.Config{Logger: logger.Default.LogMode(logger.Silent)})
	if err != nil {
		fmt.Println("open 失败:", err)
		os.Exit(1)
	}

	// 1) 表名是否与 GORM 约定一致
	fmt.Println("clients 表名              :", db.NamingStrategy.TableName("Client"))
	fmt.Println("ClientDeploymentProfile 表名:", db.NamingStrategy.TableName("ClientDeploymentProfile"))

	// 2) 模拟 admin:listClients 的读取路径（getClientBasicInfo 的 Order 链）
	var clients []models.Client
	if err := db.Order("weight ASC").Order("created_at ASC").Order("uuid ASC").Find(&clients).Error; err != nil {
		fmt.Println("查询 clients 失败:", err)
		os.Exit(1)
	}
	fmt.Printf("读到 clients 行数: %d\n", len(clients))
	for _, c := range clients {
		fmt.Printf("  uuid=%s name=%q token_len=%d rc_enabled=%v weight=%d autoName=%v\n",
			c.UUID, c.Name, len(c.Token), c.RemoteControlEnabled, c.Weight, c.NameAutoGenerated)
	}

	// 3) 部署配置读取路径
	var profile models.ClientDeploymentProfile
	for _, c := range clients {
		err := db.First(&profile, "client = ?", c.UUID).Error
		fmt.Printf("  %s 部署配置: err=%v revision=%d status=%q config_len=%d\n",
			c.UUID, err, profile.Revision, profile.DeliveryStatus, len(profile.Config))
	}

	// 4) 逐个检查可能因 NULL 触发扫描错误的列
	type colCheck struct{ name string }
	checks := []string{"remote_control_enabled", "name_auto_generated", "hidden", "weight", "auto_renewal", "region_override"}
	for _, col := range checks {
		var count int64
		q := fmt.Sprintf("SELECT COUNT(*) FROM clients WHERE %s IS NULL", col)
		if err := db.Raw(q).Scan(&count).Error; err != nil {
			fmt.Printf("  列 %s: 检查失败 %v\n", col, err)
			continue
		}
		if count > 0 {
			fmt.Printf("  ⚠ 列 %s 有 %d 行为 NULL（GORM 扫描可能出错）\n", col, count)
		}
	}
	fmt.Println("校验结束")
}
